---
- name: Pull Filtron image
  docker_image:
    name: "{{ searx_filtron_container_image }}:{{ searx_filtron_container_tag }}"
    source: pull

- name: Start filtron Docker Container
  docker_container:
    name: "{{ searx_filtron_container_name }}"
    image: "{{ searx_filtron_container_image }}:{{ searx_filtron_container_tag }}"
    command: "{{ searx_filtron_command }}"
    ports:
      - "127.0.0.1:4040:4040"
      - "127.0.0.1:4041:4041"
    volumes:
      - "{{ searx_filtorn_volume }}/rules.json:/etc/filtron/rules.json:rw"
    read_only: true
    cap_drop:
      - ALL
    network_mode: "{{ searx_network_name }}"
    networks:
      - name: "{{ searx_network_name }}"
        aliases:
          - "{{ searx_filtron_container_name }}"
    networks_cli_compatible: yes
    purge_networks: yes
    restart_policy: "unless-stopped"
    state: started
    restart: yes
    labels:
      network: "searx"
      project: "searx"
...