---
- name: Create directory for Filtron
  file:
    path: "{{ searx_filtorn_volume }}"
    state: directory
    mode: '0755'

- name: Copy filtron rules.json
  copy:
    src: rules.json
    dest: "{{ searx_filtorn_volume }}/rules.json"
    owner: root
    group: root
    mode: '0644'
...